# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd1ecc97f41b136e9cc48f037f31fd726797a856c8b179929bb9f05711d8cb380be3315d565d4f00628f10d3e54268475f5c55e89d3d19930af773e9c7485fff

test:
  secret_key_base: 8b235ffa5cb88b3215a38c089c0618f287b7020d90816e9e8a6ef774e211f93bd4eb22e673924c7e0525c80a83a8646b0f0808295e1eb92a19181a9d9923e76f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
